### PR TITLE
Add random stuff

### PR DESCRIPTION
**Pull request by DeibittoX**
Added overview component file.

### CODE REVIEW

**Comment by Dora821** [comment]
Great comments Bodgan!

**Comment by bogdangordin** [comment]
This looks well!

**Review by Dora821 — APPROVED** [review]
Great comments

**Review by bogdangordin — APPROVED** [review]
nice comment!

**Review by DanielEsquivelReynoso — COMMENTED** [review]
Terrible

**Review by DanielEsquivelReynoso — APPROVED** [review]
Great work!

**Pull request merged**
